- name: ansible-pull alle 30 min relativ zum Systemstart
  ansible.builtin.cron:
    name: "ansible-pull"
    minute: "*/30"
    job: "ansible-pull -U https://gitlab.com/brg-kremszeile/ansible_client_schueler"
